- name: Upgrade all apt packages
  tags: packages
  apt:
    upgrade: dist
    force_apt_get: true
    
- name: Install packages
  tags: packages
  apt:
    update_cache: true
    name: "{{ item }}"
    state: latest
  loop:
    - lsb-release
    - software-properties-common
    - git
    - mcrypt
    - unzip
    - imagemagick
    - certbot
    - python3-certbot-nginx
    - apt-transport-https
    - ca-certificates
    - python3-pip
    - bat
    - apache2-utils

- name: Add Docker GPG apt Key
  tags: packages
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  tags: packages
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ distribution_release }} stable"
    state: present

- name: Update apt and install docker-ce
  tags: packages
  apt:
    update_cache: true
    name: docker-ce
    state: latest

- name: Install Docker Module for Python
  tags: packages
  pip:
    name: docker

# - name: Install docker-compose from official github repo
#   tags: packages
#   get_url:
#     url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
#     dest: /usr/local/bin/docker-compose
#     mode: 'u+x,g+x'
  

- name: Remove useless packages from the cache
  tags: packages
  apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  tags: packages
  apt:
    autoremove: true