- name: Pull an Umami image
  tags: umami
  docker_image:
    name: ghcr.io/mikecao/umami
    source: pull
    tag: mysql-latest

- name: Create a Umami container
  tags: umami
  docker_container:
    name: umami
    image: ghcr.io/mikecao/umami:mysql-latest
    restart_policy: unless-stopped
    restart: true
    env:
      DATABASE_URL: "mysql://root:{{ mysql.password }}@{{ domain }}:{{ mysql.port | int }}/umami"
      HASH_SALT: $2a$12$NOvlvJgRpxZ4JPr4fMsbletV6qr7UbfWojAjRg5gJuy/bb2rHIXMC
    ports:
      - "{{ umami.port }}:3000"