- name: Pull an Umami image
  tags: umami
  docker_image:
    name: ghcr.io/mikecao/umami
    source: pull
    tag: postgresql-latest

- name: Create a Umami container
  tags: umami
  docker_container:
    name: umami
    image: ghcr.io/mikecao/umami:postgresql-latest
    restart_policy: unless-stopped
    restart: true
    env:
      DATABASE_URL: "postgresql://{{ postgres.username }}:{{ postgres.password }}@postgres_server:{{ postgres.port }}/umami"
      HASH_SALT: $2a$12$NOvlvJgRpxZ4JPr4fMsbletV6qr7UbfWojAjRg5gJuy/bb2rHIXMC
    ports:
      - "{{ umami.port }}:3000"
    networks:
      - name: db_network