- name: Ensure group "docker" exists
  tags: user
  group:
    name: docker
    state: present

- name: Create a user
  tags: user
  user:
    name: "{{ user.username }}"
    password: "{{ user.password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker
    shell: /bin/bash
    state: present

- name: Create .ssh folder
  tags: user
  file:
    path: "~{{ user.username }}/.ssh"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: 0700

- name: Add public key to authorized_keys
  tags: user
  authorized_key:
    user: "{{ user.username }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Allow specific users to log in
  tags: user
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers root {{ user.username }}'
    state: present

- name: Allow connection without password
  tags: user
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    state: present

- name: Add user to sudoers file
  tags: user
  notify:
    - Reload sshd
  lineinfile:
    path: /etc/sudoers
    regexp: '^{{ user.username }}'
    line: '{{ user.username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'