- name: Update hosts
  tags: websites
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ item.host }}"
    create: yes
  loop: "{{ websites }}"

- name: Create directories for websites
  tags: websites
  file:
    path: "/var/www/{{ item.host }}"
    state: directory
    recurse: yes
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
  when: item.proxy == false
  loop: "{{ websites }}"

- name: Copy NGINX config
  tags: websites
  template:
    src: "files/nginx/templates/{{ item.config }}.j2"
    dest: "/etc/nginx/conf.d/{{ item.host }}.conf"
  loop: "{{ websites }}"
  notify:
    - Restart nginx

- name: Copy .htpasswd
  tags: websites
  template:
    src: files/nginx/.htpasswd.j2
    dest: "/etc/nginx/.htpasswd.{{ item.host }}"
    owner: root
    group: www-data
    mode: 0644
  loop: "{{ websites }}"
  when: item.basicauth != false

- name: Generate SSL
  tags: websites
  shell: "certbot --nginx --agree-tos --redirect  --email {{ user.email }} -d {{ item.host }} -d www.{{ item.host }} -q" # --force-renewal
  loop: "{{ websites }}"

- name: "Add certbot to cron"
  tags: websites
  cron:
    name: Cerbot renew
    minute: "0"
    hour: "12"
    job: "certbot renew --post-hook 'systemctl restart nginx'"


    